language: objective-c

os:
  - linux
  - osx

osx_image: xcode7.3

podfile: runtime/objc/Podfile

script:
  - xctool test -workspace Manticore.xcworkspace -scheme ManticoreContainer-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO