matrix:
  include:
    - os: linux
      language: node
      env: BUILD_ITEM=node
      node_js:
        - "4"
    - os: osx
      language: objective-c
      env: BUILD_ITEM=ios
      osx_image: xcode7.3
    - os: osx
      language: objective-c
      env: BUILD_ITEM=osx
      osx_image: xcode7.3

podfile: runtime/objc/Podfile

script:
  - ./ci/travis.sh