environment:
  nodejs_version: "4.4"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@3
  - npm install
  - git submodule update --init --recursive
  - nuget restore runtime/win/Manticore.sln
  
build:
  project: runtime/win/Manticore.sln
  